config/routes.rb
Rails.application.routes.draw do
  resources :superheroes

end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
  validates :real_name, :hero_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/superheroes_controller.rb
class SuperheroesController < ApplicationController
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]

  # GET /superheroes
  # GET /superheroes.json
  def index
    @superheroes = Superhero.all
  end

  # GET /superheroes/1
  # GET /superheroes/1.json
  def show
  end

  # GET /superheroes/new
  def new
    @superhero = Superhero.new
  end

  # GET /superheroes/1/edit
  def edit
  end

  # POST /superheroes
  # POST /superheroes.json
  def create
    @superhero = Superhero.new(superhero_params)

    respond_to do |format|
      if @superhero.save
        format.html { redirect_to @superhero, notice: 'Superhero was successfully created.' }
        format.json { render :show, status: :created, location: @superhero }
      else
        format.html { render :new }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /superheroes/1
  # PATCH/PUT /superheroes/1.json
  def update
    respond_to do |format|
      if @superhero.update(superhero_params)
        format.html { redirect_to @superhero, notice: 'Superhero was successfully updated.' }
        format.json { render :show, status: :ok, location: @superhero }
      else
        format.html { render :edit }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superheroes/1
  # DELETE /superheroes/1.json
  def destroy
    @superhero.destroy
    respond_to do |format|
      format.html { redirect_to superheroes_url, notice: 'Superhero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superhero
      @superhero = Superhero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def superhero_params
      params.require(:superhero).permit(:real_name, :hero_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheroes_helper.rb
module SuperheroesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperHeroRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/superheroes/_form.html.erb
<%= form_for(@superhero) do |f| %>
  <% if @superhero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@superhero.errors.count, "error") %> prohibited this superhero from being saved:</h2>

      <ul>
      <% @superhero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :real_name %><br>
    <%= f.text_field :real_name %>
  </div>
  <div class="field">
    <%= f.label :hero_name %><br>
    <%= f.text_field :hero_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/superheroes/edit.html.erb
<h1>Editing superhero</h1>

<%= render 'form' %>

<%= link_to 'Show', @superhero %> |
<%= link_to 'Back', superheroes_path %>

app/views/superheroes/index.html.erb
<h1>Listing superheroes</h1>

<table>
  <thead>
    <tr>
      <th>Real name</th>
      <th>Hero name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @superheroes.each do |superhero| %>
      <tr>
        <td><%= superhero.real_name %></td>
        <td><%= superhero.hero_name %></td>
        <td><%= link_to 'Show', superhero %></td>
        <td><%= link_to 'Edit', edit_superhero_path(superhero) %></td>
        <td><%= link_to 'Destroy', superhero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Superhero', new_superhero_path %>

app/views/superheroes/new.html.erb
<h1>New superhero</h1>

<%= render 'form' %>

<%= link_to 'Back', superheroes_path %>

app/views/superheroes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Real name:</strong>
  <%= @superhero.real_name %>
</p>

<p>
  <strong>Hero name:</strong>
  <%= @superhero.hero_name %>
</p>

<%= link_to 'Edit', edit_superhero_path(@superhero) %> |
<%= link_to 'Back', superheroes_path %>